image: Previous Visual Studio 2017
configuration: Release
install:
  - ps: $env:BuildNumber= $env:APPVEYOR_BUILD_NUMBER
build_script:
  - dotnet restore
  - dotnet build -c Release
  - dotnet pack -c Release
clone_depth: 1
test: on
artifacts:
- path: '**\*.nupkg'
test_script:
  - dotnet test -c Release .\HalClient.Net.Tests\HalClient.Net.Tests.csproj